version: '3.7'
services:
  api:
    container_name: flask-container
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"